### ISSUE TITLE
some help plz

### ISSUE THREAD

**Issue by Rubenne** [brandonlw/Psychson#150]
i have this problem..
C:\fw\Psychson-master>tools\DriveCom.exe /drive=l /action=SendFirmware /burner=BN07V502TAW.bin /firmware=hid.bin
Action specified: SendFirmware
Gathering information...
Reported chip type: 2307
Reported chip ID: AD-3A-18-A3-61-25
Reported firmware version: 5.02.41
Mode: Burner
Rebooting...
Sending firmware...
FATAL: System.InvalidOperationException: Header not accepted
   at DriveCom.PhisonDevice.TransferFile(Byte[] data, Byte header, Byte body) in j:\Ruben\Desktop\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 256
   at DriveCom.Startup._RunFirmware(String fileName) in j:\Ruben\Desktop\Psychson-master\DriveCom\DriveCom\Startup.cs:line 427
   at DriveCom.Startup._SendFirmware() in j:\Ruben\Desktop\Psychson-master\DriveCom\DriveCom\Startup.cs:line 378
   at DriveCom.Startup.Main(String[] args) in j:\Ruben\Desktop\Psychson-master\DriveCom\DriveCom\Startup.cs:line 114

I know i have a 2307 and that is not compatible yet but i have a 2307 burner (right?)
I'm new to this and trying just some stuff maybe i do need to do more with this burner idk

i have also tried the BN07V106M.bin and the BN07V103M.bin as firmware but same issue

its a kingston datatraveler g4 64gb
does it need to be in a usb3.0 port or doesn't it matter?

thanks in advance

/r
p.s. sorry for bad English

**Comment by zuhaib2002** [comment]
you can not burn the current state of firmware on 2307 its meant for 2303, in short you can't work with 2307 controllers with current available resources on this project  just yet.
