### ISSUE TITLE
Problems with sending firmware to USB

### ISSUE THREAD

**Issue by onbaman** [brandonlw/Psychson#171]
Hello, I am trying to create the bad USB using a patriot supersonic xpress which has the correct phison chip in it. After following the instructions i had found i had trouble sending executable through a burner image. This is the error I uncovered
FATAL: System.InvalidOperationException: Header not accepted
   at DriveCom.PhisonDevice.TransferFile(Byte[] data, Byte header, Byte body) in C:\Users\vhuynh\Documents\BADUSB\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 256
   at DriveCom.PhisonDevice.TransferFile(Byte[] data) in C:\Users\vhuynh\Documents\BADUSB\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 238
   at DriveCom.Startup._ExecuteImage(String fileName) in C:\Users\vhuynh\Documents\BADUSB\Psychson-master\DriveCom\DriveCom\Startup.cs:line 403
   at DriveCom.Startup.Main(String[] args) in C:\Users\vhuynh\Documents\BADUSB\Psychson-master\DriveCom\DriveCom\Startup.cs:line 109
This is my new reference I am using 
https://www.youtube.com/watch?v=jfIkrzxhAXg
Ideally I would not like to open up my USB because it has a weird design that would make it harder to look untampered with.

**Comment by onbaman** [comment]
So eventually through a lot of trail and error i found a solution. Not only did i not run the build.bat file, also I did not know that rubber ducky does not like to have spaces. *Note this is with the first problem i had.
