### ISSUE TITLE
FATAL Problem

### ISSUE THREAD

**Issue by konstantinosskoutelis** [brandonlw/Psychson#207]
I tried to execute everything as you describe and in the end trying to flash the firmware as such << "PATH to DriveCom.exe" /drive="Drive Letter" /action=SendFirmware /burner="PATH to our burner image" /firmware="PATH to the firmware" >> I get the error showing below. What could be the problem? Thank you in advance

```
FATAL: System.InvalidOperationException: Header not accepted
   at DriveCom.PhisonDevice.TransferFile(Byte[] data, Byte header, Byte body) in C:\Users\skout\Desktop\RUBBER DUCKY\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 256
   at DriveCom.PhisonDevice.TransferFile(Byte[] data) in C:\Users\skout\Desktop\RUBBER DUCKY\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 238
   at DriveCom.Startup._ExecuteImage(String fileName) in C:\Users\skout\Desktop\RUBBER DUCKY\Psychson-master\DriveCom\DriveCom\Startup.cs:line 403
   at DriveCom.Startup._SendFirmware() in C:\Users\skout\Desktop\RUBBER DUCKY\Psychson-master\DriveCom\DriveCom\Startup.cs:line 375
   at DriveCom.Startup.Main(String[] args) in C:\Users\skout\Desktop\RUBBER DUCKY\Psychson-master\DriveCom\DriveCom\Startup.cs:line 114
```

**Comment by nunofaria007** [comment]
I think that happens when the Burner is being sent and the device isn't on BootMode. I believe some official firmwares ignore the BF command. To check this:

- Run DriveCom with /drive="Drive Letter" argument

- Write "boot"

- Write "mode"

If it reports Firmware mode it means you can't jump to BootMode using DriveCom. If this is your case then you need to enter BootMode manually by shorting the pins (Which pins depends on the version of your micro-controller).

**Comment by konstantinosskoutelis** [comment]
Thank you for the answer. I tried it but it returns this `Gathering information...
Reported chip type: 0000
Reported chip ID: 20-AE-00-01-00-00
Reported firmware version: 111.6E.66
Mode: Unknown` .Is this Firmware mode you are talking about ?

**Comment by nunofaria007** [comment]
Which pendrive do you have? I think yours might not have a Phison micro-controller.

**Comment by konstantinosskoutelis** [comment]
Well I got mine from the Known Supported Devices https://github.com/brandonlw/Psychson/wiki/Known-Supported-Devices and it is the Sandisk Ultra 16GB USB 3.0

**Comment by nunofaria007** [comment]
Replug your pendrive and repeat the steps but this time don't write "boot". Let's see if this time it reports the chip type.

**Comment by konstantinosskoutelis** [comment]
It's still the same result. I tried multiple times the same steps but nothing changed and that's why it bothered me the most

**Comment by nunofaria007** [comment]
There is a software called ChipGenius that might give some intel on your device.

**Comment by konstantinosskoutelis** [comment]
Probably needs Chinese Language or something cause the characters do not show up

**Comment by nunofaria007** [comment]
That's strange. Can you provide a screenshot, please?

**Comment by konstantinosskoutelis** [comment]
![image](https://user-images.githubusercontent.com/23737162/45431636-c4f9ba80-b6b0-11e8-8ec7-b98ef7786043.png)

**Comment by nunofaria007** [comment]
Can you try on a more recent version of ChipGenius? That one is indeed not written in english.

**Comment by nunofaria007** [comment]
Btw, your pendrive looks like it's plugged on an HUB. Can you plug it directly on an USB port?

**Comment by konstantinosskoutelis** [comment]
![image](https://user-images.githubusercontent.com/23737162/45432513-b1e7ea00-b6b2-11e8-9eac-c2e107b36976.png)

You were right

**Comment by nunofaria007** [comment]
Now it shows up as a Mass Storage Device and with the correct vendor ID. Was it plugged on an HUB?

**Comment by konstantinosskoutelis** [comment]
No it's not

**Comment by nunofaria007** [comment]
Looks like ChipGenius can't retrieve info about the controller. Can you still use your pendrive as normal or is it bricked?

**Comment by konstantinosskoutelis** [comment]
Yes I can use it normally

**Comment by nunofaria007** [comment]
Well, you can try the GetInfo utility that comes with MPALL. That should be able to retrieve the info about your device's controller.

**Comment by SrMilton** [comment]
Yeh, I've disassembled a Sandisk Ultra 16GB USB 3.0 and I got this shit. idk if it works
![4e208daa-c251-4660-9b76-4b34dee62ec0](https://user-images.githubusercontent.com/35127424/46172290-7edc5380-c279-11e8-8f2c-1ce151456ebe.jpg)
![22720df7-1708-458f-9f31-b59b1adfa3b9](https://user-images.githubusercontent.com/35127424/46172300-83a10780-c279-11e8-9bf7-873890c602bc.jpg)
![0f5edd96-bbe4-4a70-a377-0945b069c9a3](https://user-images.githubusercontent.com/35127424/46172317-8bf94280-c279-11e8-856e-7ba1bbd22245.jpg)

**Comment by nunofaria007** [comment]
The usb controller doesn't seem to be Phison...

**Comment by konstantinosskoutelis** [comment]
Then it should definitely be removed from the list with the suggested USB drives to prevent any other misunderstandings

**Comment by nunofaria007** [comment]
The problem is that after some time, brands start to use different usb controllers in the production of the same product. In the past Sandisk Ultra 16GB USB 3.0 might have been produced using Phison controllers, and now they might be produced with different components.

**Comment by SrMilton** [comment]
Yep, I'm trying to sell this pendrive to buy another one... Please, update the list :'(

**Comment by nunofaria007** [comment]
Higly doubt that someone will update it... This project seems dead now.

**Comment by SrMilton** [comment]
Yeh, I know.. Do you think is better make a badusb or pay $45 in a rubberducky ? If badusb >>, there is some fork better than the original project ?

**Comment by nunofaria007** [comment]
I came across with this project and played a bit with it on my Phison 2307. To my knowledge there aren't any forks (at least anything worth mentioning). If you really need this that bad, then a rubberducky might be your best option (but i think 45$ is waaaaaay overpriced, specially if you want to play a prank on someone). Keep in mind that when you burn badusb firmware to your pendrive it will act as a keyboard only and you will be unable to save files on it unless you return to the original firmware (you will also need to reburn the badusb firmware whenever you want to change the payload). On that matter rubberducky has an advantage because it has and embedded sdcard slot (according to their website)..

**Comment by SrMilton** [comment]
Tks, I'll buy a Malduino Elite. 16 payloads in the same time. Price almost the same
