### ISSUE TITLE
 Windows Does Not Recognize this device after modifying firmware

### ISSUE THREAD

**Issue by 5k1ppy** [brandonlw/Psychson#225]
Hi, I went through all of the steps to configure my bad USB and before changing the firmware, I confirmed that my flash drive had the correct controller, yet now windows doesn't recognise the device at all. It tries for a while, then it gives up and the data light on my USB hub turns off. I tried it in my main PC USB port and it does nothing too. I have a few screenshots of what I found in device manager.

![image](https://user-images.githubusercontent.com/82199824/138413003-2a2034c2-4c41-4571-a1aa-720eeb49c54b.png)
![image](https://user-images.githubusercontent.com/82199824/138413038-a068c1d6-86df-4578-9cf7-40f8dab5065f.png)

Device not migrated -

Device USB\VID_13FE&PID_5201\7&504b82f&0&1 was not migrated due to partial or ambiguous match.

Last Device Instance Id: USB\VID_04F2&PID_B40E\6&3455550a&0&5
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Location Path: 
Migration Rank: 0xF000FFFF0000F120
Present: false
Status: 0xC0000719

Device configured (usb.inf) -

Device USB\VID_13FE&PID_5201\7&504b82f&0&1 was configured.

Driver Name: usb.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Driver Date: 06/21/2006
Driver Version: 10.0.19041.488
Driver Provider: Microsoft
Driver Section: Composite.Dev.NT
Driver Rank: 0xFF2003
Matching Device Id: USB\COMPOSITE
Outranked Drivers: 
Device Updated: false
Parent Device: USB\VID_2109&PID_2812\6&8edca8f&0&3

Device not started -

Device USB\VID_13FE&PID_5201\7&504b82f&0&1 had a problem starting.

Driver Name: usb.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Service: usbccgp
Lower Filters: 
Upper Filters: 
Problem: 0xA
Problem Status: 0xC0000001

![image](https://user-images.githubusercontent.com/82199824/138413211-df2634aa-8a03-43d7-ad3b-a19b822b7205.png)

I have tried several times to restore the original (dumped) firmware and I keep getting this error (my guess is that the device isn't recognised by the app since windows doesn't recognise it) -

./DriveCom.exe /drive=D /action=SendFirmware /burner=C:\Users\User\Downloads\BadUSB\Burner_Image/BN03V104M.BIN /firmware=C:\Users\User\Downloads\Psychson\originalfw.bin
Action specified: SendFirmware
Gathering information...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0006
   at DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte[] data, Int32 bytesExpected) in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 365
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Int32 bytesExpected) in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 295
   at DriveCom.PhisonDevice.RequestVendorInfo() in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 140
   at DriveCom.PhisonDevice.GetChipType() in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 170
   at DriveCom.Startup._GetInfo() in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\Startup.cs:line 384
   at DriveCom.Startup._SendFirmware() in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\Startup.cs:line 365
   at DriveCom.Startup.Main(String[] args) in C:\Users\User\Downloads\Psychson-master\DriveCom\DriveCom\Startup.cs:line 114

I have included as much detail as possible and I hope it can help as to figure out why I'm unable to use my rubber ducky. Thanks in advance :D

**Comment by 5k1ppy** [comment]
I've found an old Samsung Galaxy S5 with an OTG micro USB port that I can use so I no longer have use for these phison 2303 USBs (and I probably bricked mine anyway).
