### ISSUE TITLE
Header not accepted

### ISSUE THREAD

**Issue by alizafzali** [brandonlw/Psychson#25]
Hi

i just got this error :

C:\Psychson\tools>DriveCom.exe /drive=K /action=SendFirmware /burner=BN03V104M.BIN /firmware=fw.bin

Action specified: SendFirmware
Gathering information...
Reported chip type: 2303
Reported chip ID: 98-DE-84-93-72-57
Reported firmware version: 1.01.10
Mode: BootMode
FATAL: System.InvalidOperationException: Header not accepted
   at DriveCom.PhisonDevice.TransferFile(Byte[] data, Byte header, Byte body) in c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:line 256
   at DriveCom.PhisonDevice.TransferFile(Byte[] data) in c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:line 238
   at DriveCom.Startup._ExecuteImage(String fileName) in c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\Startup.cs:line 403
   at DriveCom.Startup._SendFirmware() in c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\Startup.cs:line 375
   at DriveCom.Startup.Main(String[] args) in c:\Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\Startup.cs:line 114

my USB stick is Patriot Supersonic BOOST 8 Gig

thanks

**Comment by brandonlw** [comment]
Try unplugging and entering boot mode again. It is possible to enter boot mode by shorting the pins yet disrupting future communication with the NAND chip, and it looks like that may be what happened here.

**Comment by alizafzali** [comment]
can you please tell me how should i do this operation ?

**Comment by grigor108** [comment]
You've got it in the docs directory. Open your usb and short the pins depicted with a knife or paperclip.

**Comment by alizafzali** [comment]
i did the operation but still no success

i get the "FATAL: System.InvalidOperationException: Header not accepted" error

**Comment by Mo-Ko** [comment]
I also got the same error even after shorting the pins. Any headsup on this issue? @brandonlw @grigor108

**Comment by brandonlw** [comment]
This can happen even after shorting the pins and getting into boot mode. What's actually happening here is that you're disrupting communication with the NAND chip, and the boot ROM is deciding to wait for new code to run. If you hold the pins for too long, or not long enough, it could leave NAND chip communication unusable until you unplug the drive and try again.

So I would recommend you keep trying until it works.

**Comment by Mo-Ko** [comment]
Would try as you guided. From your experiment can you tell me time frame during which we need to keep pins short.
Thanks for writing back to me

-------- Original message --------

**Comment by brandonlw** [comment]
About one second. I anticipate when the LED will become lit and lift the metal object from the pins right as it comes on.

I've been hoping to make a video showing a successful boot by pin shorting, but I haven't had time.

**Comment by Mo-Ko** [comment]
So we don't need to have pin short at the time of rebooting during flashing the image?

-------- Original message --------

**Comment by brandonlw** [comment]
You only need to short the pins when plugging in the device. Once the LED stays lit (which indicates you are in boot mode), you don't need to short the pins anymore.

**Comment by anomynous5** [comment]
can someone please make a walkthrough video showing how to do it
