### ISSUE TITLE
2251-07 (2307)

### ISSUE THREAD

**Issue by aspcartman** [brandonlw/Psychson#6]
Moving 2307 from #3 to here.

**Comment by Tesrym** [comment]
Will be watching this for the sake of DataTraveler 111.

**Comment by ehennenfent** [comment]
I too eagerly await 2251-07 support, given that several devices reported to contain the 2251-03 seem to ship with the 2251-07 (looking at you, Kingston DT100G3/8GB). I appreciate all the hard work the devs have put into this, and can't wait to see where the project goes in the future.

**Comment by raif7** [comment]
count me in!!

**Comment by vikwin** [comment]
I would be interested in this too, because I just bought a Kingston DT100G3 looking forward to flash it. I am a developer, I would contribute to this if someone provides me the basic information needed for a port.

**Comment by brandonlw** [comment]
PS2251-07 support would require disassembling and studying firmware for that controller, and implementing any changes found. It's easier said than done.

I'm torn on whether to close this issue as we aren't actively exploring support for this controller, but my guess is that it's more likely to work with minor changes than other versions -- I suppose I'll leave it open for now.

**Comment by ehennenfent** [comment]
Just purchased a Patriot 8GB Supersonic Xpress and found it contains a PS2251-07 controller. Updated the wiki page to match this.

**Comment by WeldFire** [comment]
I would be interested in this.

**Comment by B00sterman** [comment]
I would love to see this. Just got my 16GB Patriot Supersonic Xpress and its a 07.

**Comment by doxmills** [comment]
Damn I can't find one damn model thumbdrive that has the right version. If anyone finds it you'd be doing yourself good by buying as many as you can and reselling them as I know people would pay a markup for guaranteed versions that work, preferably not the 32-64-128gb but the like 4-8-16gb ones that are cheap and therefor not as big of a deal if you loose one.

Even the patriot linked to from the recommended thumb drives section that goes to Amazon here:
http://www.amazon.com/gp/product/B005EWB15W/

In the questions section someone posted a couple months ago, so recent, that it comes with:
PS2251-07 (2307) v 1.09.10.

And by the looks of it all of the thumb drives now come with 2307 not 2303, so that said I'm really hoping someone reverse engineers the 2307 like mentioned by a mod in another post on here it would at least be closer to the 2303 then just reverse engineering a completely different make. Heck I'd even donate some Bitcoin lol.

Does ANYBODY know ANYWHERE that sells any thumb drive with the correct versioning for this to work? Any model on Amazon or eBay or any store that someone found recently still selling the correct version ones for this code to work? Please help a brother out. Yes I already have a Ducky but wanted to try this. Was really looking forward to it and about to order a bunch of those patriots from Amazon since they were even USB 3.0 with great speed reviews but came accross the question/answer posted on the items Amazon page saying its PS2251-07 (2307) v 1.09.10.

Thanks in advance to anyone, seriously much appreciated!

**Comment by brammittendorff** [comment]
Count me in to

**Comment by mijailr** [comment]
Me to, i see the PS2251-03 is discontinued, so many thumbs will have the PS2251-07. Will be nice to have a port guide, so we can write the code.

**Comment by H8to** [comment]
Maybe this helps?

http://vivibit.net/psychson/
http://vivibit.net/psychson2/
http://vivibit.net/psychson2307/

I'm stuck at setting the correct bit to bypass pseudo encryption on the binary though.

If somebody does get it working feel free to share in English :+1:

**Comment by Nathansswell** [comment]
Just found this today, started working on it myself. Got all the hex code into the .c files. I'm just gonna spend a lot of time double checking work so I don't brick my drive from my own mistakes. If it works, I'll write an English tutorial.

**Comment by noilex** [comment]
Hey guys! Anyone had any success following the guide from vivibit? I'm stuck at the firmware upload: getting this error
```
FATAL: System.InvalidOperationException: Header not accepted
   at DriveCom.PhisonDevice.TransferFile(Byte[] data, Byte header, Byte body) in C:\usb\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 256
   at DriveCom.PhisonDevice.TransferFile(Byte[] data) in C:\usb\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 238
   at DriveCom.Startup._ExecuteImage(String fileName) in C:\usb\Psychson-master\DriveCom\DriveCom\Startup.cs:line 403
   at DriveCom.Startup._SendFirmware() in C:\usb\Psychson-master\DriveCom\DriveCom\Startup.cs:line 375
   at DriveCom.Startup.Main(String[] args) in C:\usb\Psychson-master\DriveCom\DriveCom\Startup.cs:line 114
```
Can someone elaborate on the process of reverse engineering firmware like this? Where do I start? Thanks
