### ISSUE TITLE
DeviceIoControl failed: 0079 (Custom Payload Error)

### ISSUE THREAD

**Issue by Ozuru** [brandonlw/Psychson#72]
Hello,

I recently purchased http://www.amazon.com/gp/product/B005EWB15W/ and started working on it today. I was working on the custom payload one (the first option/tutorial) and have been having some issues. I was having errors on reboot regarding _SendCommand but I managed to fix them.

Here's the log:

P:\BadUSB\Psychson>DriveCom.exe /drive=G /action=SendFirmware /burner=BN07V106M.
BIN /firmware=hid.bin
Action specified: SendFirmware
Gathering information...
Reported chip type: 2307
Reported chip ID: 98-DE-98-92-72-50
Reported firmware version: 1.02.10
Mode: BootMode
Rebooting...
Sending firmware...
Executing...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0079
   at DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte
[] data, Int32 bytesExpected)
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Byte[] data)
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd)
   at DriveCom.PhisonDevice.JumpToPRAM()
   at DriveCom.Startup._RunFirmware(String fileName)
   at DriveCom.Startup._SendFirmware()
   at DriveCom.Startup.Main(String[] args)

My controller is a PS2251-07-V, shortened as PS2251-07 or PS2207 from what I've seen. Any ideas as to what is going on? I've tried five other burner images and all of them that allow me to get past the reboot phase trigger this error.

Thank you!

**Comment by double-pulsar** [comment]
2307 is Useless, you must use 2303

**Comment by Ozuru** [comment]
Is it a lottery of getting 2303 from that USB drive?

**Comment by double-pulsar** [comment]
@Ozuru NO,you must ask the seller,I have bought kingston G4 with 2303 is in taobao.com

**Comment by derBaecker94** [comment]
Well I got that error with my -2303. Now I cannot access it any more - there is even not the sound when pulling it into the PC. Is the only way to get it another chance by shortening the pins? How can I prevent that error - using another firmware? (I tried BN03V104M.BIN)

**Comment by gfleck** [comment]
@derBaecker94 

Until I know, we need shortcut de pins.

Only this works.

**Comment by crappy44** [comment]
You have to shortcut Pin 2 and 3. The wiki says "Hold a knife or other thin metal tool over the 2 or 3 pins in the above picture" That is a bit misunderstanding. It's NOT shortcutting 2 or 3 Pins but PIN 2 AND 3.

**Comment by weny-tang** [comment]
@zjq777007 can you tell me which web address sells kingston G4 with 2303 ?  Or can you sells me one ? thanks!
